name: Tests EasyCrypto using CI process
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode
        run: sudo Xcode-select -switch /Applications/Xcode_14.3.0.app
      - name: Build & Test
        run: xcodebuild clean build test -project EasyCrypto.xcodeproj -scheme EasyCrypto CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO